### ISSUE TITLE
Allow init() to accept ViaBackwardsConfig instead of File

### ISSUE THREAD

**Issue by MelonHell** [ViaVersion/ViaBackwards#1148]
### Problem Description

Currently, this place
https://github.com/ViaVersion/ViaBackwards/blob/1f5fd88fef3751fcc5a0c52bdc0f282cf6df428c/common/src/main/java/com/viaversion/viabackwards/api/ViaBackwardsPlatform.java#L86-L88
accepts a java.io.File, which forces us to fully duplicate the init() method in order to pass configuration not from a file.

### Solution Description

It would be much more convenient if, instead of java.io.File, this method accepted com.viaversion.viabackwards.api.ViaBackwardsConfig.

```java
    /**
     * To preserve backward compatibility
     */
    default void init(final File configFile) {
        ViaBackwardsConfig config = new ViaBackwardsConfig(configFile, getLogger());
        config.reload();
        init(config);
    }

    /**
     * Initialize ViaBackwards.
     */
    default void init(final com.viaversion.viabackwards.api.ViaBackwardsConfig config) {
        Via.getManager().getConfigurationProvider().register(config);

        ViaBackwards.init(this, config);
```

### Alternatives

As an alternative, this part of the code could be extracted into a separate method, which would also solve the problem.

https://github.com/ViaVersion/ViaBackwards/blob/1f5fd88fef3751fcc5a0c52bdc0f282cf6df428c/common/src/main/java/com/viaversion/viabackwards/api/ViaBackwardsPlatform.java#L104-L160

**Comment by florianreuth** [comment]
Done, not sure whether ViaBackwardsConfig#reload should also be moved up given it has to be called.

**Comment by MelonHell** [comment]
The problem is not solved because the method requires an implementation instead of an interface. Most likely, there was a confusion due to the same class name.
