### ISSUE TITLE
ERROR IN Protocol1_13_2To1_14 IN REMAP OF ENTITY_EQUIPMENT (0x46)

### ISSUE THREAD

**Issue by xion87** [ViaVersion/ViaBackwards#222]
**Describe the bug, provide any errors**
I just upgraded my plotsquared world from 1.13.2 to 1.15.2 without doing the chunk upgrades.
Game seem to work fine for 1.15.2 and 1.16.1 clients. But for 1.8-1.12.2 clients they crash if they are tipped in certain places o visit certain plots.
https://gist.github.com/xion87/ff7276192c2a0d97007c915534427aca

**How can we reproduce it?**
1. Login on 1.12.2 on my server
2. Teleport to any random plots, some are good but most will crash you
3. That error will appaer

**Expected behaviour**
Should not crash

**Screenshots**
Not rilevant

**ViaVersion Dump:**
https://dump.viaversion.com/a585279154a6692892bc4ebea07c7e06fee50a78433fd19e9701aca2d8366495

**Additional server info**
I am using waterfall, the server is Paper version git-Paper-373 (MC: 1.15.2), Previous version: git-Paper-655 (MC: 1.13.2)

**Comment by KennyTV** [comment]
Can you try with the latest build from https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/ ?

**Comment by KennyTV** [comment]
I will assume that is has been fixed.

**Comment by xion87** [comment]
the issue is not solved (sorry i was on vacantion)
same errror
